name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm install
      - name: Run Formatter Check
        run: npm run format
      - name: Run Linter
        run: npm run lint
      - name: Run Tests
        run: npm run test:no-watch
